[versions]
apollo-api = '1.2.6'
spigot = '1.8.8-R0.1-SNAPSHOT'
uhc-api = '1.1.0'
packetevents-api = '2.11.1'
lombok = '1.18.46'

[libraries]
apollo-api = { module = 'com.lunarclient:apollo-api', version.ref = 'apollo-api' }
spigot = { module = 'org.spigotmc:spigot', version.ref = 'spigot' }
uhc-api = { module = 'dev.kurai.uhc:uhc-api', version.ref = 'uhc-api' }
packetevents-spigot = { module = 'com.github.retrooper:packetevents-spigot', version.ref = 'packetevents-api' }
lombok = { module = 'org.projectlombok:lombok', version.ref = 'lombok' }
